### ISSUE TITLE
CRITICAL: Game is started from empty question 0 

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#19]
**Descriptions:**
Game is started from empty question 0 instead question 1. 

**Environment:** 
Version 0.0.2

**STR:**
1. Open application
2. Start game

**Actual result:**
Game is started from question 0

**Expected result:**
Game is srarted from question 1

![question0](https://user-images.githubusercontent.com/38105828/38422392-3d119194-39b3-11e8-85e6-cfd5e00d43d3.png)

**Comment by Serduk** [comment]
hey, @inndunas 
**Partial fixed in build 0.0.4**
We mark Start Round and Answer as disabled, while user don't press on button next

As we discussed about some good solve for this problem, i'll implement new feature, which will fully fix and complete your expected result in this issue: https://github.com/Serduk/whatWhereWhen/issues/26

**Comment by inndunas** [comment]
@Serduk 
was checked in 0.0.4 build
