### ISSUE TITLE
LOW: Game activity: timer's work improving

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#39]
I see a reason to improve next moments in timer's work:

- [x] start minute AFTER the sound of start will be played, not simultaneously;
- [x] stop minute if user has answered the question till minute ends;
- [ ]  make timer non-active if user didn't answered the question during 1st minute. Instead of this implement availability to get some additional time (e.g. 30 seconds) OR obligation to answer the question when minute is ended;
- [x] add last 1 second, now time ends when 2 seconds are remained

**Comment by Serduk** [comment]
variant for fix http://developer.alexanderklimov.ru/android/java/timer.php

**Comment by Serduk** [comment]
Commit: cd6d70b
 [X] start minute AFTER the sound of start will be played, not simultaneously;
 [X] stop minute if user has answered the question till minute ends;
  new issue ->> make timer non-active if user didn't answered the question during 1st minute. Instead of this implement availability to get some additional time (e.g. 30 seconds) OR obligation to answer the question when minute is ended;
  [X] add last 1 second, now time ends when 2 seconds are remained

**Comment by Serduk** [comment]
please, create new issue ->> make timer non-active if user didn't answered the question during 1st minute. Instead of this implement availability to get some additional time (e.g. 30 seconds) OR obligation to answer the question when minute is ended;

**Comment by inndunas** [comment]
@Serduk checked in 1.2.1, improvements are ok.
new issue will be created as soon as possible.
closing this ticket
