### ISSUE TITLE
MAJOR: Game activity: save custom game after app closing

### ISSUE THREAD

**Issue by inndunas** [Serduk/whatWhereWhen#59]
Created by user custom game should be available for playing till the moment when user played all questions in this game or till user deleted this game.

When user played part of questions in custom game, these questions should be marked as playes and will be not reprodused after restart of this custom game.

**Comment by Serduk** [comment]
Partly fixed in 0.0.8

As we discussed with @inndunas this feature should have next logic:
1. user create custom game (for ex select 5 questions)
2. User start new custom game
3. User play 3 of 5 questions
4. User close app
5. User start game and start play his custom game again
6 we show him all of this 5 questions as new

**Comment by Serduk** [comment]
hey, @inndunas 
Please, create new issue for 2nd part of this feature:

When user played part of questions in custom game, these questions should be marked as playes and will be not reprodused after restart of this custom game.

we should complete it and describe in future

**Comment by inndunas** [comment]
@Serduk 
as was discussed, realisation of 2nd part of this feature is not needed.
1nd part was checken in 0.0.9 build.
